### ISSUE TITLE
 Value Error

### ISSUE THREAD

**Issue by Braith12** [NixV37/Amazon-price-sniper#1]
This is what comes up when I try to run the program. Any tips?

 File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 96, in checkprice
    if float(oldprice) > float(newprice):
       ^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '$488.00'

**Comment by Braith12** [comment]
it does this with both products i have

**Comment by Braith12** [comment]
This is the whole error

Traceback (most recent call last):
  File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 127, in <module>
    PriceSniper()
  File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 16, in __init__
    self.start()
  File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 117, in start
    self.getprice(product)
  File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 80, in getprice
    self.checkproduct(price, url, landingimage)
  File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 88, in checkproduct
    self.checkprice(price, productid, landingimage)
  File "C:\Users\Braith\Downloads\Amazon-price-sniper-main\main.py", line 96, in checkprice
    if float(oldprice) > float(newprice):
                         ^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '$488.00'
